config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # # see all the pets
  # get '/pets', to: 'pets#index'

  # # Add a pet
  # get '/pets/new', to: 'pets#new'
  # post '/pets', to: 'pets#create'

  # # display the pet
  # get '/pets/:id', to: 'pets#show', as: 'pet'
  # delete '/pets/:id', to: 'pets#destroy'

  # # update the pet
  # get '/pets/:id/edit', to: 'pets#edit', as: 'edit_pet'
  # patch '/pets/:id', to: 'pets#update'

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :found_at, presence: true
  validates :species, inclusion: { in: %w(dog cat crocodile cow bird rabbit) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all.order(found_at: :DESC)
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create!(pet_params)
    redirect_to pet_path(@pet)
  end

  def edit
  end

  def update
    @pet.update(pet_params)

    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def find_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :found_at, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <%= link_to 'All the found pets 🐮', pets_path, class: 'btn btn-primary' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/edit.html.erb
<%= render 'shared/form', pet: @pet %>

app/views/pets/index.html.erb
<h1>All the pets found this month :)</h1>

<%= link_to '+ a found pet', new_pet_path, class: 'btn btn-primary' %>

<ul class="mt-5">

  <% @pets.each do |pet| %>
  <li class='m-2'>
    <%= link_to pet.name, pet_path(pet) %>
    - Found on <%= pet.found_at.strftime('%A, %b %d') %>
    <%= link_to 'Edit', edit_pet_path(pet), class: 'btn btn-warning btn-xs' %>
    <%= link_to 'Destroy', pet_path(pet),
                           method: 'delete',
                           class: 'btn btn-danger btn-xs',
                           data: { confirm: 'Are you sure?'} %>
  </li>
  <% end %>
</ul>

app/views/pets/new.html.erb
<%= render 'shared/form', pet: @pet %>

app/views/pets/show.html.erb
<h1>Here is the details about:</h1>

<h2><%= @pet.name %></h2>
<h3><%= @pet.species %></h3>

<p>found at <%= @pet.address %> on <%= @pet.found_at.strftime('%A, %b %d') %></p>

app/views/shared/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name %>

  <%= f.input :address %>

  <%= f.input :species, collection: %w(dog cat crocodile rabbit cow) %>

  <%= f.input :found_at, as: :date %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>